# Theme Configuration
remote_theme: just-the-docs/just-the-docs
color_scheme: light
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Site Metadata
title: Color Palette PHP
tagline: Extract and manipulate color palettes from images with PHP
description: A powerful PHP library for extracting color palettes from images, generating color themes, and manipulating colors in multiple color spaces (RGB, HSL, CMYK, LAB)
keywords: php color palette, image color extraction, color manipulation, color themes, php library
author: parsilver
baseurl: "/color-palette-php"
url: "https://parsilver.github.io"
version: "1.0.0"

# GitHub Integration
github_username: parsilver
repository: parsilver/color-palette-php
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/parsilver/color-palette-php"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Search Configuration (lunr.js)
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Navigation Structure
nav_enabled: true
nav_sort: case_insensitive

# Breadcrumbs
heading_anchors: true
aux_links:
  "View on GitHub":
    - "//github.com/parsilver/color-palette-php"
  "Download":
    - "//github.com/parsilver/color-palette-php/archive/refs/heads/main.zip"

# Back to Top Button
back_to_top: true
back_to_top_text: "Back to top"

# Footer Content
footer_content: "Copyright &copy; 2025 parsilver. Distributed under the MIT License."

# Last Modified Date
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Table of Contents Configuration
# Enable TOC on all pages by default
toc:
  enabled: true
  h_min: 2
  h_max: 3

# Syntax Highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
    default_lang: php
    css_class: 'highlight'
    span:
      line_numbers: false

# Markdown Configuration
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Navigation Sections Configuration
# Define collection for better organization
collections:
  quick_start:
    output: true
    permalink: /:collection/:path/
  guides:
    output: true
    permalink: /:collection/:path/
  tutorials:
    output: true
    permalink: /:collection/:path/
  api:
    output: true
    permalink: /:collection/:path/
  concepts:
    output: true
    permalink: /:collection/:path/
  examples:
    output: true
    permalink: /:collection/:path/
  resources:
    output: true
    permalink: /:collection/:path/

# Just the Docs Navigation Configuration
just_the_docs:
  collections:
    quick_start:
      name: Quick Start
      nav_exclude: false
      search_exclude: false
    guides:
      name: Guides
      nav_exclude: false
      search_exclude: false
    tutorials:
      name: Tutorials
      nav_exclude: false
      search_exclude: false
    api:
      name: API Reference
      nav_exclude: false
      search_exclude: false
    concepts:
      name: Concepts
      nav_exclude: false
      search_exclude: false
    examples:
      name: Examples
      nav_exclude: false
      search_exclude: false
    resources:
      name: Resources
      nav_exclude: false
      search_exclude: false

# Sidebar Navigation Settings
nav_fold: true
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/parsilver/color-palette-php
    hide_icon: false
    opens_in_new_tab: true

# Callouts Configuration
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# SEO Settings
google_analytics: # Add your Google Analytics ID
twitter:
  username: parsilver
  card: summary

social:
  name: Color Palette PHP
  links:
    - https://github.com/parsilver/color-palette-php

# Mermaid Diagrams Support
mermaid:
  version: "9.1.6"

# Code Copy Button
enable_copy_code_button: true

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md