remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

title: Color Palette PHP
description: A powerful PHP library for extracting color palettes from images and generating color themes
show_downloads: true
github:
  repository_url: https://github.com/parsilver/color-palette-php
  zip_url: https://github.com/parsilver/color-palette-php/archive/refs/heads/main.zip
  tar_url: https://github.com/parsilver/color-palette-php/archive/refs/heads/main.tar.gz

# Navigation
nav:
  - title: Getting Started
    url: getting-started
  - title: Core Concepts
    url: core-concepts
  - title: API Reference
    url: api/
  - title: Examples
    url: examples/
  - title: Color Playground
    url: playground
  - title: GitHub
    url: https://github.com/parsilver/color-palette-php

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Custom variables
version: "1.0.0"
github_username: parsilver
repository: parsilver/color-palette-php